name: Publish

on:
  push:
    tags: "v[0-9]*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          10.0
          11.0
    - name: Restore
      run: dotnet restore GreenPng.Tests
    - name: Build
      run: dotnet build GreenPng.Tests -c Release --no-restore
    - name: Test net10.0
      run: dotnet run --project GreenPng.Tests -c Release -f net10.0 --no-build
    - name: Test net11.0
      run: dotnet run --project GreenPng.Tests -c Release -f net11.0 --no-build
    - name: Pack
      run: dotnet pack GreenPng --no-build -p:IncludeReadme=true -o Packages
    - name: Publish
      run: dotnet nuget push Packages/* --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
